version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbit1
    container_name: rabbit1
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
