server:
  port: 10001

spring:
  application:
    name: serviceA
  rabbitmq:
#    addresses: amqp://guest:guest@localhost
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-returns: true #发送者开启return确认机制
    publisher-confirm-type: correlated # 发送者开启confirm机制
